a = input('Digite algo: ')
print('o tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É númerico? ', a.isnumeric())
print('É alfabetico? :', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúscula? ', a.isupper())
print('Está em minusculo? ', a.islower())
print('Etsá capitalizada? ', a.istitle())
